### ISSUE TITLE
Professor Cannot Add Students to the 'Unassigned' Team

### ISSUE THREAD

**Issue by pdx-cs-lbryan** [capstoneteamb/capstone360#100]
Trying to add a student to the team that unassigned students are placed on to when registering causes the following error:

...prof_dashboard.py", line 87, in post
    team_name = team_name.replace("_", " ")
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by J8cob1** [comment]
Currently being fixed in refactor branch

**Comment by J8cob1** [comment]
Refactor branch has been merged and it seems like this issue is fixed
