### ISSUE TITLE
If a student is in multiple capstone sessions, the professor may not be able to view their reviews in the dashboard

### ISSUE THREAD

**Issue by pdx-cs-lbryan** [capstoneteamb/capstone360#101]
in view_review.py, when the function is grabbing the reviewer and reviewee, it only grabs the first record where they are found. This can lead to a situation where there is a mismatch in the teams, and thus the review is not visible.  (and possibly if they're both found in an earlier session, the wrong reviews being displayed)

**Comment by J8cob1** [comment]
I merged a fix that supposedly fixes this, so I will close this issue for now (we can open it back up again if I am wrong).
