### ISSUE TITLE
Form.py question text didn't show when trying to fill out a final review for the first time

### ISSUE THREAD

**Issue by J8cob1** [capstoneteamb/capstone360#103]
When filling out a final review (when I tried filling it out for the first time, right after I set the final start/end date in the professor dashboard), the "Are you proud of your accomplishment" text disappeared. The box for answering the question was still there though.

**Comment by pdx-cs-lbryan** [comment]
I see what the issue is, fix coming in soon

**Comment by pdx-cs-lbryan** [comment]
https://github.com/capstoneteamb/capstone360/pull/105

**Comment by pdx-cs-lbryan** [comment]
Resolved
