### ISSUE TITLE
You can submit negative points for students when filling out reviews

### ISSUE THREAD

**Issue by J8cob1** [capstoneteamb/capstone360#70]
Sadly, this will not be an accidental feature

**Comment by pdx-cs-lbryan** [comment]
I'll address this in a future update to form.py

**Comment by pdx-cs-lbryan** [comment]
a fix for this is currently in this branch: https://github.com/capstoneteamb/capstone360/tree/late-and-edit

**Comment by pdx-cs-lbryan** [comment]
fix is in master
