### ISSUE TITLE
Cannot mark/add a student as team lead

### ISSUE THREAD

**Issue by pdx-cs-lbryan** [capstoneteamb/capstone360#80]
I think this is some pretty important functionality to have. I don't believe there's currently a way to do it in the app. 

some stuff that could go with it:
* ensure that a team only has 1 team lead
* identify who the team lead is on dashboard

**Comment by J8cob1** [comment]
We could add some sort of ui like the remove student UI and a button to indicate the team lead. Or maybe we could have a dropdown and a button? It could be in the edit menu

**Comment by pdx-cs-lbryan** [comment]
fix is in master
