### ISSUE TITLE
The student can't log out

### ISSUE THREAD

**Issue by J8cob1** [capstoneteamb/capstone360#85]
The student doesn't have access to "Logout" button once they log in

**Comment by pdx-cs-lbryan** [comment]
there is now a log out button on the student dashboard. maybe one should be added to the review and submission page as well

**Comment by J8cob1** [comment]
That or a link back to the dashboard?

**Comment by J8cob1** [comment]
I want someone to make a decision here so I will. I say we can have a return to student dashboard link in the form.py page and one in the review page. There, the student can then click the existing logout link.
