### ISSUE TITLE
Can't delete a student in a session twice

### ISSUE THREAD

**Issue by J8cob1** [capstoneteamb/capstone360#93]
It seems that if you remove a student from a session, add them back again, and try to remove them from the same session again, it won't work.

**Comment by J8cob1** [comment]
Potential ways to go about fixing it:
1. Modify the removed)students table so that we can have duplicates
2. Refrain from adding the student to the removed table if they are already there
3. If we find that they are already there update their removed date to the current time (so their most recent date of deletion is saved)

**Comment by anguye2** [comment]
primary keys for removed_student table are student id and session id. We can fix this issue by adding removed_date as a primary key?

**Comment by J8cob1** [comment]
Solution: make removed_date a part of the primary key

**Comment by J8cob1** [comment]
This issue doesn't appear fixed yet. We never made removed_date a part of the primary key of the removed_students table.

**Comment by J8cob1** [comment]
I think this has been fixed now (a new issue can always be created, or this issue reopened, if I am wrong).
